server:
  port: 8081
spring:
  application:
    name: client1
  boot:
    admin:
      client:
        url: "http://127.0.0.1:8888"
        instance:
          prefer-ip: true

eureka:
  instance:
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

#开启hystrix功能
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS